<a href"#" class="ex5 puntero" data-toggle="modal" data-target="#miventanaolv"> <h3><font color="#61380B"></font></h3></a>

      <div class="modal fade" id="miventanaolv" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true"><!--los tres contenedores tienen que estar siempre ya que será para el llamamiento-->
      <div class="modal-dialog imgtam3">
        <div class="modal-content imgtam2" >
          <div class="modal-header"><h3>Recordatorio contraseña</h3>  </div>
          <a href="Cocina.php" data-dismiss="modal" class="btn">Cerrar</a>
          <div class="modal-body">

              <section id="miSlideolv" class="carousel slide">
                    
                    <div class="carousel-inner pop">
                      <div class="item active">
                        <h4> Introduce tu email</h4>
                        <p> </p>
                        <form  action="login.php" method ="post" enctype="multipart/form-data" onsubmit=""> 
                          <input type="text"     id="correoo" placeholder="Correo"  name="correoo"  size="50" maxlength="30"  value="" required 
                            pattern="[a-zA-Z0-9_]+([.][a-zA-Z0-9_]+)*@[a-zA-Z0-9_]+([.][a-zA-Z0-9_]+)*[.][a-zA-Z]{1,5}" ><p></p>
                            
                        
                       
                        <input class="grande mediano mini botonL" type="button" name="Aceptar" value="&nbsp;&nbsp;&nbsp;Aceptar&nbsp;&nbsp;&nbsp;" >
                        
                       </form> 
                      </div>
                      
                      
                    </div>
                    

          </section><br>    
        </div>        
      <div class="clear"></div>
    
   </div>
 </div>
</div>
   <div class="clear"></div>
        
 