
  <a href"#" class="ex5 puntero" data-toggle="modal" data-target="#miventana"> <h3><font color="#61380B">Regional</font></h3></a>

      <div class="modal fade" id="miventana" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true"><!--los tres contenedores tienen que estar siempre ya que será para el llamamiento-->
      <div class="modal-dialog imgtam3">
        <div class="modal-content imgtam2" >
          <div class="modal-header"><h4>Regional</h4>  </div>
          <a href="#" data-dismiss="modal" class="btn">Cerrar</a>
          <div class="modal-body">

                <section id="miSlide" class="carousel slide">
                    
                    <div class="carousel-inner">
                      <div class="item active"><font face="Tw Cen MT" size="4"></font>
                        <h2>Lentejas caseras con chorizo</h2>
                        <img src="Fotos/lentejas-verdura-chorizo.jpg" alt="Lentejas" class="imgtam">
                        <ul><h3>Ingredientes:</h3>
                            <li>400 gr de lentejas Pardinas.</li>
                            <li>2 zanahorias grandes.</li>
                            <li>2 dientes de ajo.</li>
                            <li>1 puerro.</li>
                            <li>2 cebollas.</li>
                            <li>1 cucharada de pimentón de la Vera dulce.</li>
                            <li>4 cucharadas de aceite de Oliva.</li>
                            <li>1 pimiento rojo.</li>
                            <li>1 tomates maduro.</li>
                            <li>1 trozo de panceta.</li>
                            <li>1 chorizo.</li>
                            <li>2 patatas medianas.</li>
                            <li>Agua y sal.</li>
                        </ul>

                        
                        <h4>Preparación:</h4>
                        <p class="pop">
                        
                          Dejamos nuestras lentejas en remojo durante la noche, normalmente 12 horas. (Si son lentejas pardinas no es necesario, pero remojandolas se cocinarán media hora más rápido).Al día siguiente las escurrimos y las reservamos.
                          <br>  Picamos la cebolla y el ajo en trozos muy pequeños. Los ponemos en el fondo de la olla y en un chorro de aceite de oliva los doramos.
                          <br>Pelamos y troceamos las zanahorias y el tomate. También troceamos el pimiento rojo.
                          <br>Añadimos a la olla el pimiento, el tomate, las zanahorias y el puerro (partido en dos trozos grandes). Sofreímos durante un par de minutos.
                          <br>Añadimos una cucharadita de pimentón de la Vera dulce. Removemos durante un minuto cubrimos con agua fría hasta llenar la mitad de la olla.
                          <br>Dejamos que empiecen a hervir y agregamos nuestras lentejas y nuestra panceta. Salamos al gusto.
                          <br>Cuando lleven media hora cociendo añadimos a la olla el chorizo, cortado en rodajas grandes, y las patatas, peladas y cortadas en tacos grandes. Dejamos que se cocinen lentamente a temperatura media durante media hora más removiendo de vez en cuando.
                          <br>Probamos las lentejas y si es necesario correjimos de sal o añadimos algo de tiempo a la cocción y ya tenemos listas nuestras lentejas caseras con chorizo.
                          <br></br>
                          ¡¡¡¡¡¡  SI SE TIENE QUE AÑADIR AGUA (o caldo)  ...... SIEMPRE FRIA   !!!!!!
                          <br></br>
                          <br></br>

                        </p>
                      </div>
                      <div class="item"><font face="Tw Cen MT" size="4"></font>
                        <h2>Cazuela de Merluza Tradicional</h2>
                        <img src="Fotos/cazuela-merluza.jpg" alt="Merluza a la Cazuela" class="imgtam">
                        
                        <ul><h3>Ingredientes:</h3>
                          <li>5 medallones de merluza.</li>
                          <li>250 ml de caldo de pescado.</li>
                          <li>3 dientes de ajo.</li>
                          <li>2 patatas medianas.</li>
                          <li>1 pimiento verde tipo italiano.</li>
                          <li>1 cebolla.</li>
                          <li>1 cucharada de perejil picado.</li>
                          <li>1 cucharada de harina.</li>
                          <li>1 cucharadita de pimentón.</li>
                          <li>Aceite de oliva y sal.</li>
                        </ul>  
                        <h4>Preparacion:</h4>
                        <p class="pop">Pelamos los dientes de ajo y la cebolla, los pícamos muy finos picamos también el pimiento verde.
                        En una cazuela ancha , en abundante aceite de oliva lo pochamos bien. Con cuidado de que no se nos queme.
                        <br> Cuando la cebolla y el ajo estén pochados añadimos la harina y cocinamos durante un minuto sin dejar de revolver.
                        <br> Añadimos el perejil picado y el pimentón, cocinamos medio minuto más.
                        <br> A continuación pelamos y partimos las patatas el láminas gruesas. Las salamos y las colocamos en la base de la cazuela.Agregamos el caldo de pescado y salámos al gusto. Dejamos a fuego medio 5 minutos más.
                        <br>Salamos las rodajas de merluza y los añadimos a la cazuela. Cocinamos durante 5 minutos más y ya tenemos nuestra cazuela de merluza tradicional lista para servir. 

                        </p>  
                        
                      </div>
                      <div class="item"><font face="Tw Cen MT" size="4"></font>
                        <h2>Pollo en salsa</h2>
                        <img src="Fotos/pollo en salsa.jpg" alt="Merluza a la Cazuela" class="imgtam">
                        <ul><h3>Ingredientes:</h3>
                          <li>1 pollo troceado.</li>
                          <li>1 cabeza de ajos.</li>
                          <li>1 cebolla.</li>
                          <li>1 vasito de vino blanco.</li>
                          <li>Una pizca de canela en rama( del tamaño de un garbanzo).</li>
                          <li>Dos clavos de olor.</li>
                          <li>10 g de pimienta.</li>
                          <li>10 almendras picaditas.</li>
                          <li>Sal y pimienta molida al gusto.</li>
                          <li>1 hoja de laurel.</li>
                          <li>Aceite de oliva.</li>
                        </ul>  
                        <h4>Preparación:</h4>
                        <p class="pop">Paso 1: Salpimentar el pollo, cortar la mitad de los ajos en rodajas e introducirlos dentro de los trozos ( si no os gusta micho el ajo, no lo hagais). Reservar.<br>

Paso 2: En una cazuela poner aceite y freir la hoja de laurel con la cebolla cortada en trozos grandes. Apartar cuando estén fritas y reservar la cebolla.<br>

Paso 3: En el mismo aceite, freir los trozos de pollo hasta que estén dorados, añadir el vino, un poco de agua, la canela, los clavos y la pimienta en grano. Dejar cocer a fuego lento hasta que el pollo esté tierno ( unos 30 minutos) y la salsa haya espesado.<br>

Paso 4: Antes de servir, machacamos en un mortero el resto de los ajos fritos, los trozos de cebolla que habíamos reservado y las almendras y lo añadimos a la salsa y ya está listo para comer.

                        </p> 
                      </div>
                      
                    </div>
                    <a href="#miSlide" class="left carousel-control" data-slide="prev"><span class="glyphicon glyphicon-chevron-left"></span></a>
                    <a href="#miSlide" class="right carousel-control" data-slide="next"><span class="glyphicon glyphicon-chevron-right"></span></a>

          </section><br>    
        </div>        
      
    
   </div>
 </div>
</div>
   <div class="clear"></div>
