
  <a href"#" class="ex5 puntero" data-toggle="modal" data-target="#miventanareg"> <h3><font color="#61380B">Regional</font></h3></a>

      <div class="modal fade" id="miventanareg" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true"><!--los tres contenedores tienen que estar siempre ya que será para el llamamiento-->
      <div class="modal-dialog imgtam3">
        <div class="modal-content imgtam2" >
          <div class="modal-header"><h4>Regional</h4>  </div>
          <a href="#" data-dismiss="modal" class="btn">Cerrar</a>
          <div class="modal-body">

                <section id="miSlidereg" class="carousel slide">
                    
                    <div class="carousel-inner pop">
                      <div class="item active"><font face="Tw Cen MT" size="4"></font>
                        <h2>Migas Manchegas</h2>
                        <p></p>
                        <h5>Típica receta de La Mancha, muy apetecible en épocas de frío.</h5>
                        <img src="Fotos/migas.jpg" alt="Migas" class="imgtam">
                        <ul><h3>Ingredientes: (8 comensales)</h3>
                            <li>5 barras de pan (sin picos).</li>
                            <li>5 tiras de panceta.</li>
                            <li>5 chorizos.</li>
                            <li>20 dientes de ajo.</li>
                            <li>150 ml de aceite oliva.</li>
                            <li>Una cucharadita postre de pimentón.</li>
                            <li>Un vaso de agua.</li>
                            <li>Sal.</li>                           
                        </ul>


                        <h4>Preparación:</h4>
                        <p >
                        
                          Lo primero que haremos será desmigajar las barras de pan. A continuación las mojamos con pequeñas gotas de agua y las cubrimos con un paño húmedo, dejádolas reposar al menos dos horas.
                          <br>Preparamos el chorizo en pequeños trozos al igual que la panceta, reservamos junto con los ajos sin pelar. 
                          <br>Después, calentamos el aceíte de oliva a fuego alto y freimos primeramente los ajos. 
                          <br>Cuando estén dorados los retiramos e incorporamos la panceta y posteriormente el chorizo.
                          <br>Añadimos sobre el aceite una cucharadita de pimentón a fuego mínimo (para que no se queme).
                          <br>Después añadimos un vaso de agua y reservamos el caldo obtenido a parte.
                          <br>En la sartén, echamos las migas. añadimos la panceta, el chorizo y los ajos.
                          <br>Poco a poco vamos echando el caldo que habiamos reservado anteriormente y removiendo las migas para que se impregnen.

                        </p>
                      </div>
                      <div class="item">
                        <h2>Fabes o Fabada Asturiana</h2>
                        <img src="Fotos/fabes_asturianas.jpg" alt="Fabada Asturiana" class="imgtam">
                        
                        <ul><h3>Ingredientes:</h3>
                          <li>500 g de fabes de la Granja.</li>
                          <li>250 g de Panceta curada.</li>
                          <li>2 chorizos asturianos.</li>
                          <li>2 morcillas asturianas.</li>
                          <li>Agua.</li>
                          <li>200 g de hueso de jamón.</li>
                          <li>Sal (al gusto).</li>
                          <li>3 Hebras de azafrán.</li>
                         
                        </ul>  
                        <h4>Preparacion:</h4>
                        <p>Añadimos en una cazuela, a ser posible baja y ancha (si es de barro mejor), las fabes con el agua de remojo y cubrimos con ese agua hasta que quede un par de dedos por encima de las mismas. Removemos otra vez para que se junte todo bien y calentamos a fuego alto hasta que rompa a hervir.
                        <br> Cuando empiece a hervir introducimos la panceta, los chorizos, el hueso de jamón y las morcillas (previamente pinchadas para evitar que revienten). Procurad que las morcillas y los chorizos permanezcan siempre en la parte superior pare evitar posibles roturas que nos estropearían la fabada.
                        <br> Espumeamos durante unos minutos (retiramos la espuma que normalmente contiene impurezas y a la vez desgrasamos un poco el caldo).
                        <br> Cuando lleve 1/2 hora cociendo a fuego alto le añadimos las hebras de azafrán diluidas en un poco de caldo caliente de la cazuela.
                        <br>Bajamos la temperatura de cocción y añadimos sal al gusto, es importante probar el caldo ya que hemos echado el hueso de jamón y pueden quedar saladas.
                        <br>Dejamos que las fabes se cocinen lentamente a temperatura baja durante 2 horas removiendo de vez en cuando con una cuchara de madera sin romperlas. Durante estas dos horas, añadimos agua fría en dos ocasiones para “asustar” las fabes (rompe el hervor y ayuda a su perfecta cocción).
                        <br>Probamos las fabes para ver si ya están tiernas y rectificamos de sal. Una vez probadas y tiernas apartamos del fuego y dejamos reposar una hora aproximadamente.
                        <br>A continuación retiramos los chorizos, la morcilla, la panceta y los huesos de jamón. Preparamos la carne, cortando los embutidos en rodajas generosas. Troceamos la panceta y aprovechamos la carne del hueso. Reservamos para la presentación.
                        <br>Para emplatar lo mejor es un plato hondo con la fabada y la carne encima, así de fácil.

                        </p>  
                        
                      </div>
                      <div class="item">
                        <h2>Cocido Madrileño</h2>
                        <img src="Fotos/cocido-madrileño.jpg" alt="Cocido Madrileño" class="imgtam">
                        <ul><h3>Ingredientes:</h3>
                          <li>420 gr. de garbanzos.</li>
                          <li>420 gr. de morcillo.</li>
                          <li>¼ kg. de pollo.</li>
                          <li>125 gr. de chorizo.</li>
                          <li>2 zanahorias.</li>
                          <li>Punta y hueso de jamón.</li>
                          <li>160 gr. de tocino.</li>
                          <li>1 morcilla.</li>
                          <li>1 cebolla.</li>
                          <li>1 repollo.</li>
                          <li>1 diente de ajo.</li>
                          <li>2 patatas.</li>
                        </ul>  
   
                        <h4>Preparación:</h4>
                        <p>Es indispensable para esta receta que los garbanzos sean tiernos, de modo que ponerlos en un cuenco con agua toda la noche del día anterior a preparar este plato, para que se ablanden con un poco de sal.
                        <br>Cuando estén listos, los colamos y escurrimos bien, dejándolos a un lado para cuando los necesitemos.
                        <br>Ponemos una olla grande al fuego con bastante agua, unos dos litros. Ahora lavamos los siguientes ingredientes y luego los agregamos a la olla: el tocino, la punta de jamón y sus huesos, y por último el morcillo. Ponemos a media potencia y esperamos a que empiece a hervir. Se formará espuma en el agua, así que con ayuda de una espumera la quitamos.
                        <br>Una vez retirada la espuma, agregamos los garbanzos. Reducimos la potencia a fuego bajo y dejamos que se haga todo por unas dos horas más o menos.
                        <br>En una olla aparte ponemos el repollo bien picadito, utilizando un poco del caldo que se está haciendo en el cocido, junto con el chorizo y la morcilla. Dejarlo cocer.
                        <br>Cuando el cocido de la olla principal lleve alrededor de una, pelamos y lavamos las patatas, que troceamos y agregamos. Las zanahorias las pelamos y limpiamos también con agua, para agregarlas enteras. Por último echar el pollo. Si vemos que nos vamos quedando sin agua, tenemos que agregar más, pero para no estropear el plato tenéis que agregarla caliente.
                        <br>Pasado el tiempo de cocción de los garbanzos, el caldo lo echamos en una cacerola aparte, donde podemos usarlo para hacer fideos o arroz. Repartimos todo lo que tenemos de la segunda olla, así como los garbanzos que hemos cocido, en los distintos platos. Luego cubrimos con el caldo y, en el caso de que hayamos hecho fideos o arroz también lo ponemos.
                        <br>Ahora solo falta ocuparnos del ajo, que lo pelamos, picamos y servimos con el repollo.
                        <br>Lo que es el pollo, las patatas y la zanahoria se puede colocar en una bandeja y que cada persona se ponga lo que desee en el plato. O bien se puede repartir directamente en la cocina, como mejor lo veáis vosotros.


                        </p> 
                      </div>
                      
                    </div>
                    <a href="#miSlidereg" class="left carousel-control" data-slide="prev"><span class="glyphicon glyphicon-chevron-left"></span></a>
                    <a href="#miSlidereg" class="right carousel-control" data-slide="next"><span class="glyphicon glyphicon-chevron-right"></span></a>

          </section><br>    
        </div>        
      
    
   </div>
 </div>
</div>
   <div class="clear"></div>
